### ISSUE TITLE
Problem with graphics library and potential solution.

### ISSUE THREAD

**Issue by andrewadair13** [smimram/strid#2]
Hi, I had a bit of trouble getting this to work on my system (macOS 11.2.1), due to the error "Unbound module Graphics" produced during the execution of "ocamlopt -c -dtypes wire.ml" after the initial "make" command.

After some effort I managed to make everything work by adding "INCDIRS = /Users/{username}/.opam/4.11.1/lib/graphics" to "strid-master/src/Makefile"

I'm not sure if this is a common error or not; the other issue mentions a problem with graphics but doesn't offer specifics.
